### ISSUE TITLE
Version 2.0.2-1.18.2 crashes upon launch

### ISSUE THREAD

**Issue by Jeebanana** [Rabbitminers/Extended-Cogs#46]
**Describe the bug**
Only happens using the version 2.0.2-1.18.2. I just downloaded the mods listed below and used fabric, the versions below 2.0.2 does not crash

Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'extendedgears'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at com.rabbitminers.extendedgears.ExtendedCogwheels.init(ExtendedCogwheels.java:37)
	at com.rabbitminers.extendedgears.fabric.ExtendedCogwheelsFabric.onInitialize(ExtendedCogwheelsFabric.java:13)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: extendedgears:bırch_cogwheel
	at net.minecraft.class_2960.<init>(class_2960.java:41)
	at net.minecraft.class_2960.<init>(class_2960.java:50)
	at com.simibubi.create.foundation.block.BlockStressDefaults.lambda$setImpact$0(BlockStressDefaults.java:46)
	at com.tterrag.registrate.builders.Builder.transform(Builder.java:231)
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks.lambda$commonCogwheelTransformer$2(ExtendedCogwheelsBlocks.java:52)
	at com.tterrag.registrate.builders.Builder.transform(Builder.java:231)
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks.lambda$woodenCogwheelTransformer$5(ExtendedCogwheelsBlocks.java:61)
	at com.tterrag.registrate.builders.Builder.transform(Builder.java:231)
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks.lambda$static$10(ExtendedCogwheelsBlocks.java:76)
	at com.rabbitminers.extendedgears.base.datatypes.CogwheelMaterialList.<init>(CogwheelMaterialList.java:20)
	at com.rabbitminers.extendedgears.base.datatypes.WoodenBlockList.<init>(WoodenBlockList.java:11)
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks.<clinit>(ExtendedCogwheelsBlocks.java:74)
	... 10 more
**To Reproduce**
1: Launch minecraft
![Adsız](https://github.com/Rabbitminers/Extended-Cogwheels/assets/98596267/312096ae-afce-42c7-8c28-e9b62be969ec)

**Expected behavior**
The game will crash

**Screenshots**

**Loader & Other Mods:**
   Fabric
Mods: [Screenshot1](https://media.discordapp.net/attachments/528824569021333517/1111094621007781948/image.png?width=230&height=472) [Screenshot2](https://media.discordapp.net/attachments/528824569021333517/1111094621242675300/image.png?width=386&height=473)

Happy hunting

**Comment by Rabbitminers** [comment]
Also for future reference please make sure that the mod lists are legible after compression. Makes it a bit of an ordeal de-bugging :)
