### ISSUE TITLE
Startup crash with Create v0.5.1 (MC 1.19.2)

### ISSUE THREAD

**Issue by thebrightspark** [Rabbitminers/Extended-Cogs#52]
**Describe the bug**
After updating Create to v0.5.1b, the game fails to startup due to the error below.

**To Reproduce**
1. Install Create v0.5.1b + Create: Extended Cogwheels v2.0.2-1.19.2-0.5.0
2. Run the game

**Expected behavior**
The game runs without issue.

**Screenshots**
None

**Loader & Other Mods:**
 - Forge v43.2.8
 - Create v0.5.1b
 - Many others that are unrelated

**Additional context**
Relevent Logs:
```
[16:13:48] [modloading-worker-0/ERROR]: Could not find parent com/simibubi/create/content/contraptions/relays/elementary/CogWheelBlock for class com/rabbitminers/extendedgears/cogwheels/CustomCogwheelBlock in classloader cpw.mods.modlauncher.TransformingClassLoader@3d2f3dcb on thread Thread[modloading-worker-0,5,main]
[16:13:48] [modloading-worker-0/ERROR]: An error occurred building event handler
java.lang.ClassNotFoundException: com.simibubi.create.content.contraptions.relays.elementary.CogWheelBlock
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:92) ~[eventbus-6.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-6.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.3.jar:6.0.3+6.0.3+master.039e4ea9]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks.lambda$static$10(ExtendedCogwheelsBlocks.java:75) ~[extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar%23296!/:?]
	at com.rabbitminers.extendedgears.base.datatypes.CogwheelMaterialList.<init>(CogwheelMaterialList.java:20) ~[extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar%23296!/:?]
	at com.rabbitminers.extendedgears.base.datatypes.WoodenBlockList.<init>(WoodenBlockList.java:11) ~[extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar%23296!/:?]
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks.<clinit>(ExtendedCogwheelsBlocks.java:74) ~[extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar%23296!/:?]
	at com.rabbitminers.extendedgears.forge.ExtendedCogwheelsForge.<init>(ExtendedCogwheelsForge.java:20) ~[extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar%23296!/:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.8.jar%23359!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.8.jar%23358!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[16:13:48] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: extendedgears, class com.rabbitminers.extendedgears.forge.ExtendedCogwheelsForge
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.8.jar%23359!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.8.jar%23358!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/simibubi/create/content/contraptions/relays/elementary/CogWheelBlock
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks.lambda$static$10(ExtendedCogwheelsBlocks.java:75) ~[extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar%23296!/:?]
	at com.rabbitminers.extendedgears.base.datatypes.CogwheelMaterialList.<init>(CogwheelMaterialList.java:20) ~[extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar%23296!/:?]
	at com.rabbitminers.extendedgears.base.datatypes.WoodenBlockList.<init>(WoodenBlockList.java:11) ~[extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar%23296!/:?]
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks.<clinit>(ExtendedCogwheelsBlocks.java:74) ~[extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar%23296!/:?]
	at com.rabbitminers.extendedgears.forge.ExtendedCogwheelsForge.<init>(ExtendedCogwheelsForge.java:20) ~[extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar%23296!/:?]
	... 14 more
Caused by: java.lang.ClassNotFoundException: com.simibubi.create.content.contraptions.relays.elementary.CogWheelBlock
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:119) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks.lambda$static$10(ExtendedCogwheelsBlocks.java:75) ~[extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar%23296!/:?]
	at com.rabbitminers.extendedgears.base.datatypes.CogwheelMaterialList.<init>(CogwheelMaterialList.java:20) ~[extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar%23296!/:?]
	at com.rabbitminers.extendedgears.base.datatypes.WoodenBlockList.<init>(WoodenBlockList.java:11) ~[extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar%23296!/:?]
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks.<clinit>(ExtendedCogwheelsBlocks.java:74) ~[extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar%23296!/:?]
	at com.rabbitminers.extendedgears.forge.ExtendedCogwheelsForge.<init>(ExtendedCogwheelsForge.java:20) ~[extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar%23296!/:?]
	... 14 more
```

Full log file: [latest.log](https://github.com/Rabbitminers/Extended-Cogwheels/files/11725149/latest.log)

**Comment by FooterManDev** [comment]
#51

**Comment by Tesver50** [comment]
Extended coghweels does not work with Create 5.1 and will not work until it's updated and it will be updated once create 5.1 gets out on fabric

**Comment by MattDev-974** [comment]
> Extended coghweels does not work with Create 5.1 and will not work until it's updated and it will be updated once create 5.1 gets out on fabric

Crap i will just remove this mod
![Capture d'écran 2023-06-20 190142](https://github.com/Rabbitminers/Extended-Cogwheels/assets/105660629/0ba43a6c-4e94-4e41-b3b2-a87042003164)

**Comment by thebrightspark** [comment]
> Extended coghweels does not work with Create 5.1 and will not work until it's updated and it will be updated once create 5.1 gets out on fabric

There's Fabric releases for 0.5.1b now, as of a couple days ago:
https://modrinth.com/mod/create-fabric/versions?l=fabric&g=1.19.2

**Comment by TheInfamousAlk** [comment]
Getting this error with create 0.5.1b on fabric.

**Comment by jomin398** [comment]
gatting error to me too. on forge.

**Comment by Sunconure11** [comment]
@Rabbitminers

**Comment by Sunconure11** [comment]
Extended Flywheels also certainly needs an update, too.

**Comment by mortifia** [comment]
after 8 months not update
rip, little mod
