### ISSUE TITLE
Game Crashes on Launch using Create 1.20.1 0.5.1.f

### ISSUE THREAD

**Issue by Saint4desu** [Rabbitminers/Extended-Cogs#79]
**Describe the bug**
Game Crashes on Launch due to incompatibility with the new Create update. Create 1.20.1 0.5.1.f

**To Reproduce**
1: Install [Create: Extended Cogwheels 2.1.0-1.20.1-0.5.1.c-forge](https://modrinth.com/mod/extended-cogwheels/version/2.1.0-1.20.1-0.5.1.c-forge)
2: Install [Create 1.20.1 0.5.1.f](https://modrinth.com/mod/create/version/1.20.1-0.5.1.f)
3. Game Crashes on launch

**Expected behavior**
Launch without crashing. 

**Screenshots**
![image](https://github.com/Rabbitminers/Extended-Cogwheels/assets/103520633/8132d132-1724-4ca9-92aa-b406546422ae)
![image](https://github.com/Rabbitminers/Extended-Cogwheels/assets/103520633/37ea3a0b-2814-4fde-8d20-50be20fa2f9c)

**Loader & Other Mods:**
 - Forge
 Mods Used:
 Create 1.20.1 0.5.1.f
Create: Extended Cogwheels 2.1.0-1.20.1-0.5.1.c-forge

**Additional context**

`---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2023-11-05 20:07:32
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.2.1-universal.jar%23165!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:143) ~[forge-1.20.1-47.2.1-universal.jar%23165!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:421) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.2.1-universal.jar%23165!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:954) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-1.20.1-47.2.1.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.rabbitminers.extendedgears.registry.forge.ExtendedCogwheelsCreativeModeTabsImpl.useBaseTab(ExtendedCogwheelsCreativeModeTabsImpl.java:52) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23159!/:?] {re:classloading}
-- MOD create --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: Could not initialize class com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks
		at com.simibubi.create.AllBlocks.redirect$zba000$changeLayerType(AllBlocks.java:2424) ~[create-1.20.1-0.5.1.f.jar%23158!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:A}
		at com.simibubi.create.AllBlocks.<clinit>(AllBlocks.java:354) ~[create-1.20.1-0.5.1.f.jar%23158!/:0.5.1.f] {re:mixin,re:classloading,pl:mixin:A}
		at com.simibubi.create.Create.onCtor(Create.java:108) ~[create-1.20.1-0.5.1.f.jar%23158!/:0.5.1.f] {re:classloading}
		at com.simibubi.create.Create.<init>(Create.java:93) ~[create-1.20.1-0.5.1.f.jar%23158!/:0.5.1.f] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.1.jar%23162!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.1.jar%23161!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

	Mod File: /C:/Users/Saint/AppData/Roaming/com.modrinth.theseus/profiles/Create Bug/mods/create-1.20.1-0.5.1.f.jar
	Failure message: Create (create) has failed to load correctly
		java.lang.NoClassDefFoundError: Could not initialize class com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks
	Mod Version: 0.5.1.f
	Mod Issue URL: https://github.com/Creators-of-Create/Create/issues
	Exception message: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)' [in thread "modloading-worker-0"]
Stacktrace:
	at com.rabbitminers.extendedgears.registry.forge.ExtendedCogwheelsCreativeModeTabsImpl.useBaseTab(ExtendedCogwheelsCreativeModeTabsImpl.java:52) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23159!/:?] {re:classloading}
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsCreativeModeTabs.useBaseTab(ExtendedCogwheelsCreativeModeTabs.java) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23159!/:?] {re:classloading}
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks.<clinit>(ExtendedCogwheelsBlocks.java:37) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23159!/:?] {re:classloading,re:mixin}
	at com.rabbitminers.extendedgears.ExtendedCogwheels.init(ExtendedCogwheels.java:33) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23159!/:?] {re:classloading}
	at com.rabbitminers.extendedgears.forge.ExtendedCogwheelsForge.<init>(ExtendedCogwheelsForge.java:24) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23159!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.1.jar%23162!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.1.jar%23161!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

-- MOD extendedgears --
Details:
	Mod File: /C:/Users/Saint/AppData/Roaming/com.modrinth.theseus/profiles/Create Bug/mods/extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar
	Failure message: Extended Cogwheels (extendedgears) has failed to load correctly
		java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)'
	Mod Version: 2.1.0-1.20.1-0.5.1.c-forge
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)'
Stacktrace:
	at com.rabbitminers.extendedgears.registry.forge.ExtendedCogwheelsCreativeModeTabsImpl.useBaseTab(ExtendedCogwheelsCreativeModeTabsImpl.java:52) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23159!/:?] {re:classloading}
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsCreativeModeTabs.useBaseTab(ExtendedCogwheelsCreativeModeTabs.java) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23159!/:?] {re:classloading}
	at com.rabbitminers.extendedgears.registry.ExtendedCogwheelsBlocks.<clinit>(ExtendedCogwheelsBlocks.java:37) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23159!/:?] {re:classloading,re:mixin}
	at com.rabbitminers.extendedgears.ExtendedCogwheels.init(ExtendedCogwheels.java:33) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23159!/:?] {re:classloading}
	at com.rabbitminers.extendedgears.forge.ExtendedCogwheelsForge.<init>(ExtendedCogwheelsForge.java:24) ~[extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar%23159!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.1.jar%23162!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.1.jar%23161!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.9, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 172945480 bytes (164 MiB) / 526385152 bytes (502 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900XT 12-Core Processor           
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3699
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 72693.30
	Virtual memory used (MB): 20646.53
	Swap memory total (MB): 40000.00
	Swap memory used (MB): 86.56
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.1.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.1.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.1.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.1.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.1.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.20.1-47.2.1-universal.jar                 |Forge                         |forge                         |47.2.1              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |COMMON_SET|Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |ERROR     |Manifest: NOSIGNATURE
		extendedgears-2.1.0-1.20.1-0.5.1.c-forge.jar      |Extended Cogwheels            |extendedgears                 |2.1.0-1.20.1-0.5.1.c|ERROR     |Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: c2acca72-e459-406b-92b4-aab7348abd80
	FML: 47.2
	Forge: net.minecraftforge:47.2.1`

**Comment by SunkenHero** [comment]
To my knowledge, EB is not compatible with Create 0.5.1**c** and higher, you would need to wait or downgrade to 0.5.1**b**

**Comment by FernLeafie** [comment]
This is extended cogwheels tho, so the compatibility of extended bogeys isn't really applicable

**Comment by SunkenHero** [comment]
> This is extended cogwheels tho, so the compatibility of extended bogeys isn't really applicable

oh im sorry, i missread your issue.

**Comment by Flexz9** [comment]
Is there an update planned to create 0.5.1f?

**Comment by mxnmnm** [comment]
You can find a temporary fix here https://discord.com/channels/1069326955742244884/1069327973817262250/1198009860009230437

**Comment by TrickShow** [comment]
> You can find a temporary fix here https://discord.com/channels/1069326955742244884/1069327973817262250/1198009860009230437
What discord is this in @mxnmnm

**Comment by mxnmnm** [comment]
> > You can find a temporary fix here https://discord.com/channels/1069326955742244884/1069327973817262250/1198009860009230437
> > What discord is this in @mxnmnm

The discord for this mod
https://discord.com/invite/GJsQadv9Mc

Although I have recently run into issues with it. Creative mode might crash in some scenarios because of something related to the tabs and you might experience lag spikes (likely an issue related to another mod but this mod is definitely involved in some way)
